#!/usr/bin/env python3
"""Phase 8 item 1: rewrite every 'phonetic' field across all data files to hold
Thai-script transliteration (how the word sounds, written in Thai script for
Thai readers) instead of IPA. Field NAME is kept as 'phonetic' everywhere
(see Phase 8 commit message for why); only the VALUE's meaning changes.
"""
import json
import re

# ---------------------------------------------------------------------------
# Word-level Thai transliteration dictionary. Keys are lowercased English
# tokens (contractions kept whole, e.g. "don't"). Multi-syllable single
# words use internal hyphens per Thai-dictionary convention (e.g. "บิว-ทิ-ฟุล"
# for "beautiful"); multi-word phrases are composed by joining looked-up
# tokens with spaces (composition happens later in this script).
# ---------------------------------------------------------------------------
WORD_TH = {}


def add(pairs):
    for k, v in pairs.items():
        WORD_TH[k.lower()] = v


# ---- vocabulary.json word list (300) ----
add({
    # greetings
    "hello": "เฮล-โล",
    "good": "กู๊ด",
    "morning": "มอร์-นิ่ง",
    "evening": "อีฟ-นิ่ง",
    "thank": "แธงค์",
    "you": "ยู",
    "goodbye": "กู๊ด-บาย",
    "please": "พลีส",
    "afternoon": "อาฟ-เทอร์-นูน",
    "night": "ไนท์",
    "how": "ฮาว",
    "are": "อาร์",
    "i'm": "ไอม์",
    "fine": "ไฟน์",
    "thank you,": "แธงค์-กิว",
    "nice": "ไนซ์",
    "to": "ทู",
    "meet": "มีท",
    "see": "ซี",
    "later": "เล-เทอร์",
    "excuse": "เอ็ก-สคิวส์",
    "me": "มี",
    "sorry": "ซอ-รี่",
    "you're": "ยัวร์",
    "welcome": "เวล-คัม",
    "what's": "วอทส์",
    "your": "ยัวร์",
    "name": "เนม",
    "is": "อิส",
    "sarah": "ซาร่าห์",
    "where": "แวร์",
    "from": "ฟรอม",
    "don't": "โดนท์",
    "understand": "อัน-เดอร์-สแตนด์",
    "can": "แคน",
    "repeat": "รี-พีท",
    "that": "แดท",
    # family
    "mother": "มา-เธอร์",
    "father": "ฟา-เธอร์",
    "sister": "ซิส-เทอร์",
    "brother": "บรา-เธอร์",
    "grandmother": "แกรนด์-มา-เธอร์",
    "grandfather": "แกรนด์-ฟา-เธอร์",
    "son": "ซัน",
    "daughter": "ดอ-เทอร์",
    "husband": "ฮัส-แบนด์",
    "wife": "ไวฟ์",
    "aunt": "อานท์",
    "uncle": "อัง-เคิล",
    "cousin": "คัส-ซิน",
    "niece": "นีซ",
    "nephew": "เนฟ-ฮิว",
    "baby": "เบ-บี้",
    "parents": "แพ-เรินท์ส",
    "children": "ชิล-เดรน",
    "grandparents": "แกรนด์-แพ-เรินท์ส",
    "grandchild": "แกรนด์-ไชลด์",
    # food
    "apple": "แอป-เปิล",
    "bread": "เบรด",
    "water": "วอ-เทอร์",
    "rice": "ไรซ์",
    "chicken": "ชิค-เค่น",
    "coffee": "คอฟ-ฟี่",
    "milk": "มิลค์",
    "egg": "เอ็กก์",
    "fish": "ฟิช",
    "beef": "บีฟ",
    "vegetable": "เวจ-จิ-เท-เบิล",
    "fruit": "ฟรุต",
    "tea": "ที",
    "juice": "จูซ",
    "soup": "ซุป",
    "salad": "แซล-ลาด",
    "noodles": "นู้ด-เดิลส์",
    "cheese": "ชีส",
    "butter": "บัท-เทอร์",
    "sugar": "ชู-การ์",
    # numbers
    "one": "วัน",
    "two": "ทู",
    "three": "ทรี",
    "four": "ฟอร์",
    "five": "ไฟว์",
    "six": "ซิกซ์",
    "seven": "เซ-เว่น",
    "eight": "เอท",
    "nine": "ไนน์",
    "ten": "เทน",
    "eleven": "อี-เลฟ-เว่น",
    "twelve": "ทเวลฟ์",
    "thirteen": "เธอร์-ทีน",
    "fourteen": "ฟอร์-ทีน",
    "fifteen": "ฟิฟ-ทีน",
    "sixteen": "ซิก-ทีน",
    "seventeen": "เซ-เว่น-ทีน",
    "eighteen": "เอ-ทีน",
    "nineteen": "ไนน์-ทีน",
    "twenty": "ทเวน-ที",
    # colors
    "red": "เรด",
    "orange": "ออ-เรนจ์",
    "yellow": "เยล-โลว์",
    "green": "กรีน",
    "blue": "บลู",
    "purple": "เพอร์-เพิล",
    "pink": "พิงค์",
    "brown": "บราวน์",
    "black": "แบล็ค",
    "white": "ไวท์",
    "gray": "เกรย์",
    "gold": "โกลด์",
    "silver": "ซิล-เวอร์",
    "light": "ไลท์",
    "dark": "ดาร์ค",
    "turquoise": "เทอร์-ควอยซ์",
    "beige": "เบจ",
    "navy": "เน-วี่",
    "maroon": "มา-รูน",
    "lime": "ไลม์",
    # daysTime
    "monday": "มัน-เดย์",
    "tuesday": "ทิวส์-เดย์",
    "wednesday": "เวนส์-เดย์",
    "thursday": "เธิร์ส-เดย์",
    "friday": "ไฟร-เดย์",
    "saturday": "แซท-เทอร์-เดย์",
    "sunday": "ซัน-เดย์",
    "today": "ทู-เดย์",
    "tomorrow": "ทู-มอร์-โรว์",
    "yesterday": "เยส-เทอร์-เดย์",
    "week": "วีค",
    "month": "มันธ์",
    "year": "เยียร์",
    "hour": "อาว-เออร์",
    "minute": "มิน-นิท",
    "weekend": "วีค-เอนด์",
    # weather
    "sunny": "ซัน-นี่",
    "rainy": "เรน-นี่",
    "cloudy": "คลาว-ดี้",
    "windy": "วิน-ดี้",
    "snowy": "สโน-วี่",
    "hot": "ฮอท",
    "cold": "โคลด์",
    "warm": "วอร์ม",
    "cool": "คูล",
    "rainbow": "เรน-โบว์",
    "umbrella": "อัม-เบรล-ล่า",
    "spring": "สปริง",
    "summer": "ซัม-เมอร์",
    "autumn": "ออ-ทัมน์",
    "winter": "วิน-เทอร์",
    "foggy": "ฟ็อก-กี้",
    "stormy": "สตอร์-มี่",
    "humid": "ฮิว-มิด",
    "thunder": "ธัน-เดอร์",
    "lightning": "ไลท์-นิ่ง",
    # house
    "house": "เฮาส์",
    "room": "รูม",
    "kitchen": "คิท-เช่น",
    "bedroom": "เบด-รูม",
    "bathroom": "บาธ-รูม",
    "living": "ลิฟ-วิ่ง",
    "door": "ดอร์",
    "window": "วิน-โดว์",
    "table": "เท-เบิล",
    "chair": "แชร์",
    "bed": "เบด",
    "sofa": "โซ-ฟา",
    "television": "เท-เล-วิช-ชั่น",
    "lamp": "แลมพ์",
    "mirror": "มิ-เรอร์",
    "garden": "การ์-เดน",
    "key": "คีย์",
    "refrigerator": "รี-ฟริจ-เจอ-เร-เทอร์",
    "shelf": "เชล์ฟ",
    "roof": "รูฟ",
    # clothing
    "shirt": "เชิ้ต",
    "t-shirt": "ที-เชิ้ต",
    "pants": "แพนท์ส",
    "dress": "เดรส",
    "skirt": "สเกิร์ท",
    "jacket": "แจ็ค-เก็ต",
    "coat": "โค้ท",
    "shoes": "ชูส์",
    "socks": "ซ็อคส์",
    "hat": "แฮท",
    "jeans": "ยีนส์",
    "shorts": "ชอร์ตส์",
    "gloves": "กลัฟส์",
    "scarf": "สการ์ฟ",
    "belt": "เบลท์",
    "sweater": "สเว-ตเตอร์",
    "underwear": "อัน-เดอร์-แวร์",
    "boots": "บูทส์",
    "sunglasses": "ซัน-กลาส-เซส",
    "pajamas": "พะ-จา-มาส์",
    # bodyHealth
    "head": "เฮด",
    "eye": "อาย",
    "ear": "เอียร์",
    "nose": "โนส",
    "mouth": "เมาธ์",
    "hand": "แฮนด์",
    "arm": "อาร์ม",
    "leg": "เล็ก",
    "foot": "ฟุต",
    "stomach": "สทัม-มัค",
    "back": "แบ็ค",
    "tooth": "ทูธ",
    "hair": "แฮร์",
    "finger": "ฟิง-เกอร์",
    "doctor": "ด็อก-เตอร์",
    "hospital": "ฮอส-พิ-เทิล",
    "sick": "ซิค",
    "heart": "ฮาร์ท",
    "medicine": "เมด-ดิ-ซิน",
    "healthy": "เฮล-ธี",
    # jobs
    "teacher": "ทีช-เชอร์",
    "nurse": "เนิร์ส",
    "police": "พะ-ลีส",
    "officer": "ออฟ-ฟิ-เซอร์",
    "chef": "เชฟ",
    "farmer": "ฟาร์ม-เมอร์",
    "driver": "ไดร-เวอร์",
    "artist": "อาร์-ทิสท์",
    "musician": "มิว-ซิช-ชั่น",
    "writer": "ไร-เทอร์",
    "student": "สทิว-เดินท์",
    "waiter": "เว-เทอร์",
    "cashier": "แค-ชเยียร์",
    "firefighter": "ไฟร์-ไฟ-เทอร์",
    "engineer": "เอน-จิ-เนียร์",
    "lawyer": "ลอย-เยอร์",
    "manager": "แมน-นิ-เจอร์",
    "pilot": "ไพ-ลัท",
    "scientist": "ไซ-เอน-ทิสท์",
    "dentist": "เดน-ทิสท์",
    "accountant": "อะ-เคาน์-เทินท์",
    # shopping
    "money": "มัน-นี่",
    "price": "ไพรซ์",
    "cheap": "ชีพ",
    "expensive": "เอ็ก-สเปน-ซิฟ",
    "buy": "บาย",
    "sell": "เซล",
    "store": "สตอร์",
    "market": "มาร์-เกต",
    "cash": "แคช",
    "bag": "แบ็ก",
    "size": "ไซซ์",
    "change": "เชนจ์",
    "sale": "เซล",
    "customer": "คัส-เทอ-เมอร์",
    "shopping": "ชอป-ปิ้ง",
    "cart": "คาร์ท",
    "wallet": "วอล-เลท",
    "receipt": "รี-ซีท",
    "discount": "ดิส-เคาท์",
    "credit": "เครด-ดิท",
    "card": "การ์ด",
    "coupon": "คู-พอน",
    # transportation
    "car": "คาร์",
    "bus": "บัส",
    "train": "เทรน",
    "airplane": "แอร์-เพลน",
    "bicycle": "ไบ-ซิ-เคิล",
    "motorcycle": "โม-เตอร์-ไซ-เคิล",
    "taxi": "แท็ก-ซี่",
    "boat": "โบ๊ท",
    "road": "โรด",
    "ticket": "ทิค-เคท",
    "station": "สเต-ชั่น",
    "airport": "แอร์-พอร์ท",
    "subway": "ซับ-เวย์",
    "ship": "ชิพ",
    "traffic": "แทรฟ-ฟิค",
    "passenger": "แพส-เซน-เจอร์",
    "parking": "พาร์ค-กิ้ง",
    "highway": "ไฮ-เวย์",
    "seatbelt": "ซีท-เบลท์",
    # hobbies
    "reading": "รี-ดิ้ง",
    "swimming": "สวิม-มิ่ง",
    "running": "รัน-นิ่ง",
    "dancing": "แดน-ซิ่ง",
    "singing": "ซิง-กิ้ง",
    "painting": "เพน-ทิ่ง",
    "fishing": "ฟิช-ชิ่ง",
    "gaming": "เกม-มิ่ง",
    "traveling": "แทรฟ-เวล-ลิ่ง",
    "drawing": "ดรอว์-อิ่ง",
    "playing": "เพลย์-อิ่ง",
    "football": "ฟุต-บอล",
    "guitar": "กี-ตาร์",
    "watching": "วอช-ชิ่ง",
    "movies": "มู-วีส์",
    "photography": "โฟ-ทอก-กระ-ฟี",
    "gardening": "การ์-เดน-นิ่ง",
    "hiking": "ไฮ-กิ้ง",
    "yoga": "โย-กะ",
    "camping": "แคม-ปิ้ง",
    "cycling": "ไซ-คลิ่ง",
    "knitting": "นิท-ติ้ง",
    # feelings
    "happy": "แฮพ-พี",
    "sad": "แซด",
    "angry": "แอง-กรี",
    "excited": "เอ็ก-ไซ-เท็ด",
    "nervous": "เนอร์-เวิส",
    "tired": "ไทร์ด",
    "bored": "บอร์ด",
    "surprised": "เซอร์-ไพรส์ด",
    "scared": "สแกร์ด",
    "relaxed": "รี-แลกซ์ด",
    "confused": "คอน-ฟิวส์ด",
    "proud": "พราวด์",
    "embarrassed": "เอ็ม-แบ-รัสท์",
    "worried": "เวอร์-รีด",
    "confident": "คอน-ฟิ-เดินท์",
    "jealous": "เจล-ลัส",
    "lonely": "โลน-ลี่",
    "grateful": "เกรท-ฟุล",
    "disappointed": "ดิส-อะ-พอยน์-เท็ด",
    "curious": "คิว-เรียส",
})

# ---- verbs.json / adjectives.json forms ----
add({
    "eat": "อีท", "eats": "อีทส์", "ate": "เอท", "eating": "อีท-ทิ่ง",
    "go": "โก", "goes": "โกส์", "went": "เวนท์", "going": "โก-อิ่ง", "gone": "กอน",
    "have": "แฮฟ", "has": "แฮส", "had": "แฮด", "having": "แฮฟ-วิ่ง",
    "do": "ดู", "does": "ดัส", "did": "ดิด", "doing": "ดู-อิ่ง",
    "write": "ไรท์", "writes": "ไรทส์", "wrote": "โรท", "writing": "ไร-ทิ่ง",
    "speak": "สปีค", "speaks": "สปีคส์", "spoke": "สโปค", "speaking": "สปี-กิ้ง",
    "drink": "ดริงค์", "drinks": "ดริงค์ส", "drank": "แดรงค์", "drinking": "ดริง-กิ้ง",
    "play": "เพลย์", "plays": "เพลย์ส", "played": "เพลย์ด", "playing": "เพลย์-อิ่ง",
    "watch": "วอช", "watches": "วอช-เชส", "watched": "วอชท์", "watching": "วอช-ชิ่ง",
    "study": "สทัด-ดี้", "studies": "สทัด-ดีส", "studied": "สทัด-ดีด", "studying": "สทัด-ดี้-อิ่ง",
    "work": "เวิร์ค", "works": "เวิร์คส์", "worked": "เวิร์คท์", "working": "เวิร์ค-กิ้ง",
    "read": "รีด", "reads": "รีดส์", "reading": "รี-ดิ้ง",
    "listen": "ลิส-เซิ่น", "listens": "ลิส-เซินส์", "listened": "ลิส-เซินด์", "listening": "ลิส-เซิ่น-นิ่ง",
    "cook": "คุค", "cooks": "คุคส์", "cooked": "คุคท์", "cooking": "คุค-กิ้ง",
    "want": "วอนท์", "wants": "วอนท์ส", "wanted": "วอน-ทิด", "wanting": "วอน-ทิ่ง",
    "make": "เมค", "makes": "เมคส์", "made": "เมด", "making": "เม-กิ้ง",
    "big": "บิก", "bigger": "บิก-เกอร์", "biggest": "บิก-เกสท์",
    "small": "สมอล", "smaller": "สมอล-เลอร์", "smallest": "สมอล-เลสท์",
    "tall": "ทอล", "taller": "ทอล-เลอร์", "tallest": "ทอล-เลสท์",
    "fast": "ฟาสท์", "faster": "ฟาสท์-เทอร์", "fastest": "ฟาสท์-เทสท์",
    "old": "โอลด์", "older": "โอลด์-เดอร์", "oldest": "โอลด์-เดสท์",
    "young": "ยัง", "younger": "ยัง-เกอร์", "youngest": "ยัง-เกสท์",
    "beautiful": "บิว-ทิ-ฟุล", "more beautiful": "มอร์ บิว-ทิ-ฟุล", "most beautiful": "โมสท์ บิว-ทิ-ฟุล",
    "expensive": "เอ็ก-สเปน-ซิฟ", "more expensive": "มอร์ เอ็ก-สเปน-ซิฟ", "most expensive": "โมสท์ เอ็ก-สเปน-ซิฟ",
    "interesting": "อิน-เทอ-เรส-ติ้ง", "more interesting": "มอร์ อิน-เทอ-เรส-ติ้ง", "most interesting": "โมสท์ อิน-เทอ-เรส-ติ้ง",
    "difficult": "ดิฟ-ฟิ-คัลท์", "more difficult": "มอร์ ดิฟ-ฟิ-คัลท์", "most difficult": "โมสท์ ดิฟ-ฟิ-คัลท์",
    "comfortable": "คัม-ฟอร์-เทอ-เบิล", "more comfortable": "มอร์ คัม-ฟอร์-เทอ-เบิล", "most comfortable": "โมสท์ คัม-ฟอร์-เทอ-เบิล",
    "popular": "พอพ-พิว-ล่าร์", "more popular": "มอร์ พอพ-พิว-ล่าร์", "most popular": "โมสท์ พอพ-พิว-ล่าร์",
    "good": "กู๊ด", "better": "เบท-เทอร์", "best": "เบสท์",
    "bad": "แบด", "worse": "เวิร์ส", "worst": "เวิร์สท์",
    "far": "ฟาร์", "farther": "ฟาร์-เธอร์", "farthest": "ฟาร์-เธสท์",
    "much": "มัช", "many": "เมน-นี่", "little": "ลิท-เทิล", "least": "ลีสท์",
})

# ---- function / grammar words needed for full sentences ----
add({
    "a": "อะ", "an": "แอน", "the": "เดอะ", "and": "แอนด์", "but": "บัท", "or": "ออร์",
    "not": "น็อท", "no": "โน", "yes": "เยส", "so": "โซ", "if": "อิฟ", "as": "แอส",
    "at": "แอท", "in": "อิน", "on": "ออน", "of": "ออฟ", "for": "ฟอร์", "with": "วิธ",
    "by": "บาย", "about": "อะ-เบาท์", "from": "ฟรอม", "to": "ทู", "into": "อิน-ทู",
    "over": "โอ-เวอร์", "under": "อัน-เดอร์", "near": "เนียร์", "nearby": "เนียร์-บาย",
    "before": "บิ-ฟอร์", "after": "อาฟ-เทอร์", "until": "อัน-ทิล", "since": "ซินซ์",
    "again": "อะ-เกน", "always": "ออล-เวย์ส", "never": "เน-เวอร์", "often": "ออฟ-เฟิ่น",
    "usually": "ยู-ชวล-ลี่", "sometimes": "ซัม-ไทม์ส", "already": "ออล-เร-ดี้",
    "still": "สทิล", "just": "จัสท์", "only": "โอน-ลี่", "also": "ออล-โซ", "too": "ทู",
    "very": "เว-รี่", "really": "รี-อัล-ลี่", "quite": "ไคว้ท์", "so": "โซ",
    "i": "ไอ", "you": "ยู", "he": "ฮี", "she": "ชี", "it": "อิท", "we": "วี", "they": "เดย์",
    "me": "มี", "him": "ฮิม", "her": "เฮอร์", "us": "อัส", "them": "เดม",
    "my": "มาย", "your": "ยัวร์", "his": "ฮิส", "its": "อิทส์", "our": "อาว-เออร์", "their": "แดร์",
    "this": "ดิส", "that": "แดท", "these": "ดีส", "those": "โดส", "here": "เฮียร์", "there": "แดร์",
    "who": "ฮู", "what": "วอท", "when": "เวน", "where": "แวร์", "why": "วาย", "how": "ฮาว", "which": "วิช",
    "am": "แอม", "is": "อิส", "are": "อาร์", "was": "วอส", "were": "เวอร์", "be": "บี", "been": "บีน", "being": "บี-อิ่ง",
    "will": "วิล", "would": "วุด", "can": "แคน", "could": "คุด", "should": "ชุด", "must": "มัสท์", "may": "เมย์", "might": "ไมท์",
    "do": "ดู", "does": "ดัส", "did": "ดิด", "done": "ดัน",
    "don't": "โดนท์", "doesn't": "ดัส-เซินท์", "didn't": "ดิด-เดินท์",
    "isn't": "อิส-เซินท์", "aren't": "อาร์-เนินท์", "wasn't": "วอส-เซินท์", "weren't": "เวอร์-เรินท์",
    "can't": "แคนท์", "couldn't": "คุด-เดินท์", "won't": "โวนท์", "wouldn't": "วุด-เดินท์",
    "shouldn't": "ชุด-เดินท์", "haven't": "แฮฟ-เวินท์", "hasn't": "แฮส-เซินท์", "hadn't": "แฮด-เดินท์",
    "i'm": "ไอม์", "i'd": "ไอด์", "i'll": "ไอล์", "i've": "ไอฟ์",
    "you're": "ยัวร์", "you'll": "ยูล", "you've": "ยูฟ์", "you'd": "ยูด",
    "he's": "ฮีส", "she's": "ชีส", "it's": "อิทส์", "that's": "แดทส์", "there's": "แดร์ส",
    "we're": "เวียร์", "we've": "วีฟ", "we'll": "วีล", "we'd": "วีด",
    "they're": "แดร์", "they've": "เดฟ", "they'll": "เดล",
    "who's": "ฮูส", "what's": "วอทส์", "here's": "เฮียร์ส", "where's": "แวร์ส", "how's": "ฮาวส์",
    "let's": "เล็ทส์", "that'll": "แดทเทิล",
    "come": "คัม", "comes": "คัมส์", "came": "เคม", "coming": "คัม-มิ่ง",
    "get": "เก็ท", "gets": "เก็ทส์", "got": "ก็อท", "getting": "เก็ท-ทิ่ง",
    "give": "กิฟ", "gives": "กิฟส์", "gave": "เกฝ", "giving": "กิฟ-วิ่ง",
    "take": "เทค", "takes": "เทคส์", "took": "ทุค", "taking": "เท-คิ่ง",
    "know": "โนว์", "knows": "โนวส์", "knew": "นิว", "knowing": "โนว์-อิ่ง",
    "think": "ธิงค์", "thinks": "ธิงค์ส", "thought": "ธอท", "thinking": "ธิง-กิ้ง",
    "see": "ซี", "sees": "ซีส์", "saw": "ซอ", "seeing": "ซี-อิ่ง", "seen": "ซีน",
    "look": "ลุค", "looks": "ลุคส์", "looked": "ลุคท์", "looking": "ลุค-กิ้ง",
    "find": "ไฟนด์", "finds": "ไฟนด์ส", "found": "ฟาวนด์", "finding": "ไฟนด์-ดิ่ง",
    "need": "นีด", "needs": "นีดส์", "needed": "นี-เด็ด", "needing": "นี-ดิ่ง",
    "help": "เฮลพ์", "helps": "เฮลพ์ส", "helped": "เฮลพ์ท", "helping": "เฮล-ปิ้ง",
    "try": "ทราย", "tries": "ทรายส์", "tried": "ทรายด์", "trying": "ทราย-อิ่ง",
    "call": "คอล", "calls": "คอลส์", "called": "คอลด์", "calling": "คอล-ลิ่ง",
    "keep": "คีพ", "keeps": "คีพส์", "kept": "เค็พท์", "keeping": "คี-ปิ้ง",
    "let": "เล็ท", "lets": "เล็ทส์", "letting": "เล็ท-ทิ่ง",
    "start": "สทาร์ท", "starts": "สทาร์ทส์", "started": "สทาร์ท-เท็ด", "starting": "สทาร์ท-ทิ่ง",
    "stop": "สทอพ", "stops": "สทอพส์", "stopped": "สทอพท์", "stopping": "สทอพ-ปิ้ง",
    "show": "โชว์", "shows": "โชวส์", "showed": "โชว์ด", "showing": "โชว์-อิ่ง",
    "ask": "อาสก์", "asks": "อาสก์ส", "asked": "อาสก์ท", "asking": "อาส-กิ้ง",
    "answer": "อาน-เซอร์", "answers": "อาน-เซอร์ส", "answered": "อาน-เซอร์ด",
    "follow": "ฟอล-โลว์", "follows": "ฟอล-โลวส์", "followed": "ฟอล-โลว์ด", "following": "ฟอล-โลว์-อิ่ง",
    "walk": "วอค", "walks": "วอคส์", "walked": "วอคท์", "walking": "วอ-กิ้ง",
    "run": "รัน", "runs": "รันส์", "running": "รัน-นิ่ง",
    "sit": "ซิท", "sits": "ซิทส์", "sitting": "ซิท-ทิ่ง",
    "sleep": "สลีพ", "sleeps": "สลีพส์", "slept": "สเลพท์", "sleeping": "สลี-ปิ้ง",
    "swim": "สวิม", "swims": "สวิมส์", "swimming": "สวิม-มิ่ง",
    "sing": "ซิง", "sings": "ซิงส์", "sang": "แซง", "singing": "ซิง-กิ้ง",
    "wear": "แวร์", "wears": "แวร์ส", "wore": "วอร์", "wearing": "แวร์-ริ่ง",
    "live": "ลิฝ", "lives": "ลิฝส์", "lived": "ลิฝด์", "living": "ลิฝ-วิ่ง",
    "travel": "แทรฟ-เวิล", "travels": "แทรฟ-เวิลส์", "traveled": "แทรฟ-เวิลด์", "traveling": "แทรฟ-เวล-ลิ่ง",
    "visit": "วิส-ซิท", "visits": "วิส-ซิทส์", "visited": "วิส-ซิ-เท็ด",
    "marry": "แม-รี่", "marries": "แม-รีส์", "married": "แม-รีด",
    "improve": "อิม-พรูฟ", "improves": "อิม-พรูฟส์", "improved": "อิม-พรูฟด์",
    "practice": "แพรค-ทิส", "practices": "แพรค-ทิส-เซส", "practiced": "แพรค-ทิสท์",
    "feel": "ฟีล", "feels": "ฟีลส์", "felt": "เฟลท์", "feeling": "ฟี-ลิ่ง",
    "sound": "ซาวด์", "sounds": "ซาวด์ส",
    "seem": "ซีม", "seems": "ซีมส์",
    "prefer": "พรี-เฟอร์", "prefers": "พรี-เฟอร์ส", "preferred": "พรี-เฟอร์ด",
    "hear": "เฮียร์", "hears": "เฮียร์ส", "heard": "เฮิร์ด", "hearing": "เฮีย-ริ่ง",
    "miss": "มิส", "misses": "มิส-เซส", "missed": "มิสท์",
    "remember": "รี-เมม-เบอร์", "remembers": "รี-เมม-เบอร์ส", "remembered": "รี-เมม-เบอร์ด",
    "forget": "ฟอร์-เก็ท", "forgets": "ฟอร์-เก็ทส์", "forgot": "ฟอร์-กอท",
    "leave": "ลีฝ", "leaves": "ลีฝส์", "left": "เลฟท์", "leaving": "ลี-ฝวิ่ง",
    "arrive": "อะ-ไรฝ์", "arrives": "อะ-ไรฝ์ส", "arrived": "อะ-ไรฝ์ด",
    "drive": "ไดรฝ์", "drives": "ไดรฝ์ส", "drove": "โดรฝ", "driving": "ไดรฝ-วิ่ง",
    "ride": "ไรด์", "rides": "ไรด์ส", "rode": "โรด", "riding": "ไร-ดิ่ง",
    "catch": "แคทช์", "catches": "แคทช์-เชส", "caught": "คอท",
    "carry": "แค-รี่", "carries": "แค-รีส์", "carried": "แค-รีด",
    "bring": "บริง", "brings": "บริงส์", "brought": "บรอท", "bringing": "บริง-กิ้ง",
    "pay": "เพย์", "pays": "เพย์ส", "paid": "เพด", "paying": "เพย์-อิ่ง",
    "save": "เซฝ", "saves": "เซฝส์", "saved": "เซฝด์",
    "book": "บุค", "books": "บุคส์", "booked": "บุคท์", "booking": "บุค-กิ้ง",
    "cancel": "แคน-เซิล", "cancels": "แคน-เซิลส์", "cancelled": "แคน-เซิลด์",
    "accept": "แอค-เซพท์", "accepts": "แอค-เซพท์ส",
    "fill": "ฟิล", "fills": "ฟิลส์", "filled": "ฟิลด์", "filling": "ฟิล-ลิ่ง",
    "sign": "ไซน์", "signs": "ไซน์ส", "signed": "ไซน์ด",
    "check": "เช็ค", "checks": "เช็คส์", "checked": "เช็คท์",
    "withdraw": "วิธ-ดรอ", "withdraws": "วิธ-ดรอส",
    "open": "โอ-เพ่น", "opens": "โอ-เพ่นส์", "opened": "โอ-เพ่นด์",
    "close": "โคลส", "closes": "โคล-เซส", "closed": "โคลสด์",
    "flown": "โฟลน", "flying": "ฟลาย-อิ่ง", "fly": "ฟลาย", "flew": "ฟลู", "flies": "ฟลายส์",
    "boil": "บอยล์", "boils": "บอยล์ส", "boiling": "บอย-ลิ่ง",
    "freeze": "ฟรีซ", "freezes": "ฟรีซ-เซส", "froze": "โฟรซ", "frozen": "โฟรเซ่น",
    "melt": "เมลท์", "melts": "เมลท์ส", "melted": "เมล-เท็ด",
    "expand": "เอ็ก-สแพนด์", "expands": "เอ็ก-สแพนด์ส", "expanded": "เอ็ก-สแพน-เด็ด",
    "evaporate": "อี-แวพ-โพ-เรท", "evaporates": "อี-แวพ-โพ-เรทส์",
    "rise": "ไรส์", "rises": "ไรส์-เซส", "risen": "ริส-เซ่น",
    "set": "เซท", "sets": "เซทส์",
    "die": "ได", "dies": "ไดส์", "died": "ไดด์",
    "hurt": "เฮิร์ท", "hurts": "เฮิร์ทส์",
    "touch": "ทัช", "touches": "ทัช-เชส", "touched": "ทัชท์",
    "mix": "มิกซ์", "mixes": "มิกซ์-เซส", "mixed": "มิกซ์ท์",
    "hurry": "เฮอ-รี่", "hurries": "เฮอ-รีส์", "hurried": "เฮอ-รีด",
    "worry": "เวอ-รี่", "worries": "เวอ-รีส์", "worried": "เวอ-รีด",
    "promise": "พรอม-มิส", "promises": "พรอม-มิส-เซส", "promised": "พรอม-มิสท์",
    "appreciate": "แอพ-พรี-ชี-เอท", "appreciates": "แอพ-พรี-ชี-เอทส์", "appreciated": "แอพ-พรี-ชี-เอ-เท็ด",
    # nouns / misc content words
    "airplanes": "แอร์-เพลนส์", "aisle": "ไอล์", "all": "ออล", "allergic": "อะ-เลอร์-จิค",
    "along": "อะ-ลอง", "aloud": "อะ-เลาด์", "alright": "ออล-ไรท์", "am": "แอม",
    "and": "แอนด์", "anna": "แอน-นา", "any": "เอน-นี่", "anymore": "เอน-นี่-มอร์",
    "anyone": "เอน-นี่-วัน", "anything": "เอน-นี่-ธิ่ง", "apples": "แอป-เปิลส์",
    "around": "อะ-ราวด์", "author": "ออ-เธอร์", "available": "อะ-เว-ลา-เบิล",
    "away": "อะ-เวย์", "awesome": "ออ-ซัม",
    "backpack": "แบ็ค-แพ็ค", "badminton": "แบด-มิน-ตัน", "bags": "แบ็กส์",
    "baht": "บาท", "bake": "เบค", "bakery": "เบ-เค่อ-รี่", "bank": "แบงค์",
    "beach": "บีช", "bike": "ไบค์", "birthday": "เบิร์ธ-เดย์", "boarding": "บอร์ด-ดิ้ง",
    "bottle": "บอท-เทิล", "box": "บ็อกซ์", "breakfast": "เบรค-ฟาสท์", "breeze": "บรีซ",
    "cafe": "คา-เฟ่", "cake": "เคค", "cards": "การ์ดส์", "cars": "คาร์ส",
    "cat": "แคท", "cats": "แคทส์", "catch": "แคทช์", "center": "เซน-เทอร์",
    "chance": "ชานซ์", "chiang": "เชียง", "choice": "ชอยซ์", "city": "ซิ-ตี้",
    "class": "คลาส", "classmates": "คลาส-เมทส์", "clean": "คลีน", "color": "คัล-เลอร์",
    "cookie": "คุ-กี้", "corner": "คอร์-เนอร์", "cough": "คอฟ", "counter": "เคาน์-เทอร์",
    "course": "คอร์ส", "cream": "ครีม", "crowded": "คราว-เด็ด", "crowds": "คราวด์ส",
    "day": "เดย์", "days": "เดย์ส", "december": "ดี-เซม-เบอร์", "dinner": "ดิน-เนอร์",
    "documents": "ด็อก-คิว-เมินท์ส", "east": "อีสท์", "easier": "อี-ซี่-เออร์",
    "else": "เอลส์", "email": "อี-เมล", "english": "อิง-กลิช", "enough": "อี-นัฟ",
    "every": "เอฟ-วรี่", "everyone": "เอฟ-วรี่-วัน", "exactly": "เอ็ก-แซ็คท์-ลี่",
    "exam": "เอ็ก-แซม", "exercise": "เอ็ก-เซอร์-ไซส์", "expected": "เอ็ก-สเปค-เท็ด",
    "favorite": "เฟ-เวอ-ริท", "fever": "ฟี-เวอร์", "few": "ฟิว", "fi": "ฟาย",
    "fifth": "ฟิฟธ์", "finish": "ฟิน-นิช", "finished": "ฟิน-นิชท์", "fire": "ไฟร์",
    "first": "เฟิร์สท์", "fits": "ฟิทส์", "fitting": "ฟิท-ทิ่ง", "flavor": "เฟล-เวอร์",
    "flight": "ไฟลท์", "floor": "ฟลอร์", "food": "ฟูด", "form": "ฟอร์ม",
    "free": "ฟรี", "fridge": "ฟริดจ์", "friend": "เฟรนด์", "friends": "เฟรนด์ส",
    "fun": "ฟัน", "gate": "เกท", "great": "เกรท", "ground": "กราวนด์", "guess": "เกส",
    "hard": "ฮาร์ด", "hats": "แฮทส์", "he": "ฮี", "headache": "เฮด-เอค",
    "heat": "ฮีท", "hey": "เฮ", "hi": "ไฮ", "home": "โฮม", "hometown": "โฮม-ทาวน์",
    "homework": "โฮม-เวิร์ค", "hotel": "โฮ-เทล", "hungry": "ฮัง-กรี้",
    "ice": "ไอซ์", "iced": "ไอซ์ท์", "id": "ไอ-ดี", "idea": "ไอ-เดีย", "ideas": "ไอ-เดียส์",
    "instead": "อิน-สเต็ด", "japan": "จา-แปน", "job": "จ็อบ", "keys": "คีย์ส์",
    "kind": "ไคนด์", "kinds": "ไคนด์ส", "languages": "แลง-กวิจ-เจส", "laptop": "แลป-ท็อป",
    "large": "ลาร์จ", "last": "ลาสท์", "late": "เลท", "leather": "เล-เธอร์",
    "left": "เลฟท์", "letter": "เลท-เทอร์", "library": "ไล-เบร-รี่", "like": "ไลค์",
    "london": "ลัน-ดอน", "long": "ลอง", "lost": "ลอสท์", "lot": "ล็อท",
    "love": "ลัฝ", "lovely": "ลัฝ-ลี่", "luggage": "ลัก-กิจ", "lunch": "ลันช์",
    "mai": "ใหม่", "math": "แมธ", "maybe": "เม-บี้", "medium": "มี-เดียม",
    "merrier": "แม-รี่-เออร์", "met": "เม็ท", "metal": "เม-เทิล", "minutes": "มิน-นิทส์",
    "mondays": "มัน-เดย์ส", "movie": "มู-วี่", "music": "มิว-สิค", "mystery": "มิส-เท่อ-รี่",
    "nearest": "เนีย-เรสท์", "new": "นิว", "news": "นิวส์", "newspaper": "นิวส์-เพ-เพอร์",
    "next": "เน็กซ์ท์", "nick": "นิค", "nights": "ไนท์ส", "nothing": "นัธ-ธิ่ง",
    "novels": "นอฝ-เวิลส์", "now": "นาว", "number": "นัม-เบอร์", "o'clock": "โอ-คล็อค",
    "ocean": "โอ-ชั่น", "office": "ออฟ-ฟิส", "old": "โอลด์", "order": "ออร์-เดอร์",
    "out": "เอาท์", "outside": "เอาท์-ไซด์", "own": "โอน", "page": "เพจ",
    "pair": "แพร์", "paperwork": "เพ-เพอร์-เวิร์ค", "paragraph": "แพ-รา-กราฟ",
    "park": "พาร์ค", "part": "พาร์ท", "parties": "พาร์-ตี้ส", "party": "พาร์-ตี้",
    "pass": "พาส", "passport": "พาส-พอร์ท", "pasta": "พาส-ต้า", "peanuts": "พี-นัทส์",
    "pen": "เพน", "pencil": "เพน-ซิล", "people": "พี-เพิล", "perfect": "เพอร์-เฟ็คท์",
    "perfectly": "เพอร์-เฟ็คท์-ลี่", "phone": "โฟน", "phones": "โฟนส์", "photos": "โฟ-โทส์",
    "pizza": "พิซ-ซ่า", "plans": "แพลนส์", "plants": "แพลนท์ส", "plenty": "เพลน-ตี้",
    "pm": "พี-เอ็ม", "probably": "พรอบ-บับ-ลี่", "problem": "พรอบ-เบลิม",
    "question": "เควส-ชั่น", "rain": "เรน", "raining": "เร-นิ่ง", "rains": "เรนส์",
    "ready": "เร็ด-ดี้", "relieved": "รี-ลีฝด์", "report": "รี-พอร์ท",
    "reservation": "เรส-เซอร์-เว-ชั่น", "rest": "เรสท์", "right": "ไรท์", "rooms": "รูมส์",
    "safer": "เซฟ-เฟอร์", "salt": "ซอลท์", "sandwich": "แซนด์-วิช", "saturdays": "แซท-เทอร์-เดย์ส",
    "school": "สคูล", "sea": "ซี", "seafood": "ซี-ฟูด", "seat": "ซีท",
    "serious": "เซีย-เรียส", "she": "ชี", "shoe": "ชู", "shop": "ช็อป",
    "smith": "สมิธ", "sleeping": "สลี-ปิ้ง", "snow": "สโนว์", "some": "ซัม",
    "someday": "ซัม-เดย์", "someone": "ซัม-วัน", "something": "ซัม-ธิ่ง", "song": "ซอง",
    "soon": "ซูน", "spicy": "สไป-ซี่", "sport": "สปอร์ท", "sports": "สปอร์ทส์",
    "straight": "สเทรท", "stronger": "สตรอง-เกอร์", "students": "สทิว-เดินท์ส",
    "suitcase": "ซูท-เคส", "sun": "ซัน", "sure": "ชัวร์", "swim": "สวิม",
    "takes": "เทคส์", "tap": "แทป", "taxis": "แท็ก-ซี่ส์", "temperature": "เทม-เพอ-ระ-เจอร์",
    "tennis": "เทน-นิส", "test": "เทสท์", "text": "เท็กซ์ท์", "thai": "ไทย",
    "thailand": "ไทย-แลนด์", "than": "แดน", "thanks": "แธงค์ส", "then": "เดน",
    "thousand": "เธา-เซินด์", "time": "ไทม์", "times": "ไทม์ส", "together": "ทู-เกท-เธอร์",
    "tom": "ทอม", "tonight": "ทู-ไนท์", "turn": "เทิร์น", "turns": "เทิร์นส์",
    "tv": "ที-วี", "used": "ยูสท์", "vegetables": "เวจ-จิ-เท-เบิลส์", "view": "วิว",
    "wait": "เวท", "walking": "วอ-กิ้ง", "way": "เวย์", "wear": "แวร์",
    "weather": "เว-เธอร์", "weekends": "วีค-เอนด์ส", "well": "เวล", "wet": "เวท",
    "whole": "โฮล", "wi": "ไว", "wind": "วินด์", "wow": "วาว", "yet": "เยท",
    "sets": "เซทส์", "check": "เช็ค",
})

MULTI_WORD = {
    # for tokens that are actually two-word units in the source text but
    # regex-split into separate tokens, or for cleaner composed phrases
}

# small fixups for tokens the auto-tokenizer will hit that need a specific
# stress-pattern not covered by a generic single-word entry above
FIXUPS = {
    "sarah": "ซาร่าห์",
    "absent": "แอบ-เซินท์",
    "ac": "เอ-ซี",
    "account": "อะ-เคาน์ท์",
    "actually": "แอค-ชวล-ลี่",
    "address": "แอด-เดรส",
    "ahead": "อะ-เฮด",
    "b": "บี",
    "e": "อี",
    "early": "เออร์-ลี่",
    "happier": "แฮพ-พี้-เออร์",
    "mild": "ไมลด์",
    "moment": "โม-เมินท์",
    "more": "มอร์",
    "oh": "โอ",
    "okay": "โอ-เค",
    "stay": "สเทย์",
    "third": "เธิร์ด",
    "thirty": "เธอร์-ที",
    "yourself": "ยัวร์-เซลฟ์",
    "apartment": "อะ-พาร์ท-เมินท์",
    "dog": "ด็อก",
    "dogs": "ด็อกส์",
    "pet": "เพ็ท",
    "t": "ที",
    "careful": "แคร์-ฟุล",
    "cheaper": "ชี-เพอร์",
    "cheapest": "ชี-เพสท์",
    "happiest": "แฮพ-พี้-เอสท์",
    "less": "เลส",
    "most": "โมสท์",
}
WORD_TH.update(FIXUPS)


def th_word(tok):
    key = tok.lower()
    if key in WORD_TH:
        return WORD_TH[key]
    return None


TOKEN_RE = re.compile(r"[A-Za-z]+(?:'[A-Za-z]+)?")


def compose(text):
    """Tokenize an English phrase/sentence and join per-token Thai transliterations
    with spaces. Returns (thai_string, missing_tokens)."""
    tokens = TOKEN_RE.findall(text)
    parts = []
    missing = []
    for tok in tokens:
        th = th_word(tok)
        if th is None:
            missing.append(tok)
            parts.append(f"[{tok}]")
        else:
            parts.append(th)
    return " ".join(parts), missing


if __name__ == "__main__":
    import sys
    print(f"dictionary size: {len(WORD_TH)}")
